version: '3.10'

services:
  service_a:
    build:
      context: .
      dockerfile: Dockerfile_service_a
    command: uvicorn service_a.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./service_a/:/app/
    ports:
      - "8000:8000"
    environment:
      - TEMPO_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector

  service_b:
    build:
      context: .
      dockerfile: Dockerfile_service_b
    command: uvicorn service_b.main:app --reload --host 0.0.0.0 --port 8001
    volumes:
      - ./service_b/:/app/
    ports:
      - "8001:8001"
    environment:
      - TEMPO_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"

volumes:
  postgres_data_movie:
  postgres_data_cast: