apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
  namespace: fastapi
  labels:
    app: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: aniketdubey/service_b:latest
        env:
        - name: TEMPO_ENDPOINT
          value: "http://tempo.fastapi.svc.cluster.local:4317"
        - name: SERVICE_NAME
          value: "service-b"
        ports:
        - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: service-b-service
  namespace: fastapi
spec:
  selector:
    app: service-b
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP