apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
  namespace: fastapi
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: aniketdubey/service_a:latest
        env:
        - name: TEMPO_ENDPOINT
          value: "http://tempo.fastapi.svc.cluster.local:4317"
        - name: SERVICE_NAME
          value: "service-a"
        - name: SERVICE_B_URL"
          value: "http://service-b-service.fastapi.svc.cluster.local:8001/service_b"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-a-service
  namespace: fastapi
spec:
  selector:
    app: service-a
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP